# Generated by Django 5.0.6 on 2024-09-23 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0022_alter_tag_tag_type'),
        ('users', '0003_inbox_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox_messages',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.product'),
        ),
    ]
