# Generated by Django 5.0.6 on 2024-09-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_inbox_messages_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox_messages',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
