# Generated by Django 5.0.6 on 2024-09-18 09:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('short_discription', models.CharField(max_length=50, null=True)),
                ('discription', models.TextField(max_length=500, null=True)),
                ('main_img', models.ImageField(default='default/market.png', upload_to='iteams/')),
                ('sub_img1', models.ImageField(default='default/market.png', upload_to='iteams/')),
                ('sub_img2', models.ImageField(default='default/market.png', upload_to='iteams/')),
                ('sub_img3', models.ImageField(default='default/market.png', upload_to='iteams/')),
                ('sub_img4', models.ImageField(default='default/market.png', upload_to='iteams/')),
                ('purchase_date', models.DateField(null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
