# Generated by Django 5.0.6 on 2024-09-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ownership_type',
            field=models.CharField(choices=[('1st', '1st Owner'), ('2nd', '2nd Owner'), ('2nd+', 'More than 2nd')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='discription',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_discription',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
