# Generated by Django 5.0.6 on 2024-09-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bill_and_box',
            field=models.CharField(choices=[('Yes', 'Have either bill/box'), ('No', "I don't have bill or box")], default=None, max_length=50),
        ),
    ]
