# Generated by Django 5.0.6 on 2024-09-18 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_alter_product_bill_and_box'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bill_and_box',
        ),
    ]
