# Generated by Django 5.0.6 on 2024-09-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_product_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_type', models.CharField(choices=[('mobiles', 'Mobiles'), ('smartphones', 'Smartphones'), ('laptop', 'Laptop'), ('electronics', 'Electronics'), ('computer', 'Computer'), ('fashion_and_clothes', 'Fashion and Clothes'), ('house', 'House'), ('rent', 'Rent'), ('car', 'Car'), ('bike', 'Bike')], max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='market.tag'),
        ),
    ]
