# Generated by Django 5.0.6 on 2024-09-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_alter_tag_tag_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, to='market.tag'),
        ),
    ]
