# Generated by Django 5.0.6 on 2024-09-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0020_alter_product_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_type',
            field=models.CharField(blank=True, choices=[('mobiles', 'Mobiles'), ('smartphones', 'Smartphones'), ('laptops', 'Laptop'), ('electronics', 'Electronics'), ('computers', 'Computer'), ('fashion_and_clothes', 'Fashion and Clothes'), ('houses', 'House'), ('rentes', 'Rent'), ('cars', 'Car'), ('bikes', 'Bike')], default=None, max_length=20, null=True),
        ),
    ]
