# Generated by Django 5.0.6 on 2024-09-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0021_alter_tag_tag_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_type',
            field=models.CharField(blank=True, choices=[('mobiles', 'Mobiles'), ('smartphones', 'Smartphones'), ('laptops', 'Laptops'), ('electronics', 'Electronics'), ('computers', 'Computesr'), ('fashion_and_clothes', 'Fashion and Clothes'), ('houses', 'Houses'), ('rentes', 'Rentes'), ('cars', 'Cars'), ('bikes', 'Bikes')], default=None, max_length=20, null=True),
        ),
    ]
